# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'load1.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QProgressBar, QSizePolicy, QWidget)

class Ui_Loading_window(object):
    def setupUi(self, Loading_window):
        if not Loading_window.objectName():
            Loading_window.setObjectName(u"Loading_window")
        Loading_window.setWindowModality(Qt.WindowModal)
        Loading_window.resize(966, 455)
        Loading_window.setAcceptDrops(True)
        icon = QIcon()
        icon.addFile(u":/algorius/algorius/icone alguros-1.ico", QSize(), QIcon.Normal, QIcon.Off)
        Loading_window.setWindowIcon(icon)
        Loading_window.setWindowOpacity(0.880000000000000)
        Loading_window.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(29, 29, 29, 255), stop:0.368715 rgba(31, 31, 31, 255), stop:0.675978 rgba(38, 38, 38, 255), stop:1 rgba(63, 63, 63, 255));\n"
"\n"
"")
        Loading_window.setSizeGripEnabled(False)
        Loading_window.setModal(True)
        self.Loading_window_progressBar = QProgressBar(Loading_window)
        self.Loading_window_progressBar.setObjectName(u"Loading_window_progressBar")
        self.Loading_window_progressBar.setGeometry(QRect(180, 310, 531, 61))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Loading_window_progressBar.sizePolicy().hasHeightForWidth())
        self.Loading_window_progressBar.setSizePolicy(sizePolicy)
        palette = QPalette()
        brush = QBrush(QColor(6, 208, 164, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient = QLinearGradient(0, 0, 1, 1)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(29, 29, 29, 255))
        gradient.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient.setColorAt(1, QColor(63, 63, 63, 255))
        brush1 = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        brush2 = QBrush(QColor(0, 255, 255, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush2)
        brush3 = QBrush(QColor(112, 112, 112, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush3)
        brush4 = QBrush(QColor(255, 255, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush4)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        gradient1 = QLinearGradient(0, 0, 1, 1)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(29, 29, 29, 255))
        gradient1.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient1.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient1.setColorAt(1, QColor(63, 63, 63, 255))
        brush5 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Base, brush5)
        gradient2 = QLinearGradient(0, 0, 1, 1)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(29, 29, 29, 255))
        gradient2.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient2.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient2.setColorAt(1, QColor(63, 63, 63, 255))
        brush6 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.Window, brush6)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush)
        brush7 = QBrush(QColor(0, 0, 0, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush7)
        palette.setBrush(QPalette.Active, QPalette.Link, brush)
        brush8 = QBrush(QColor(56, 56, 56, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush8)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush3)
        brush9 = QBrush(QColor(112, 112, 112, 151))
        brush9.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush9)
#endif
        brush10 = QBrush(QColor(208, 208, 208, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush10)
        gradient3 = QLinearGradient(0, 0, 1, 1)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(29, 29, 29, 255))
        gradient3.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient3.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient3.setColorAt(1, QColor(63, 63, 63, 255))
        brush11 = QBrush(gradient3)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush11)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush4)
        brush12 = QBrush(QColor(227, 227, 227, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush12)
        brush13 = QBrush(QColor(64, 65, 66, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush13)
        brush14 = QBrush(QColor(160, 160, 160, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush14)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush10)
        brush15 = QBrush(QColor(255, 51, 51, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush15)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush10)
        gradient4 = QLinearGradient(0, 0, 1, 1)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(29, 29, 29, 255))
        gradient4.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient4.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient4.setColorAt(1, QColor(63, 63, 63, 255))
        brush16 = QBrush(gradient4)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush16)
        gradient5 = QLinearGradient(0, 0, 1, 1)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(29, 29, 29, 255))
        gradient5.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient5.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient5.setColorAt(1, QColor(63, 63, 63, 255))
        brush17 = QBrush(gradient5)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush17)
        brush18 = QBrush(QColor(105, 105, 105, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush18)
        brush19 = QBrush(QColor(29, 84, 92, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush19)
        brush20 = QBrush(QColor(240, 240, 240, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush20)
        brush21 = QBrush(QColor(0, 122, 244, 255))
        brush21.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush21)
        brush22 = QBrush(QColor(53, 54, 55, 255))
        brush22.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush22)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush13)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush10)
        brush23 = QBrush(QColor(127, 127, 128, 255))
        brush23.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush23)
#endif
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        gradient6 = QLinearGradient(0, 0, 1, 1)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(29, 29, 29, 255))
        gradient6.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient6.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient6.setColorAt(1, QColor(63, 63, 63, 255))
        brush24 = QBrush(gradient6)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush24)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        gradient7 = QLinearGradient(0, 0, 1, 1)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(29, 29, 29, 255))
        gradient7.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient7.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient7.setColorAt(1, QColor(63, 63, 63, 255))
        brush25 = QBrush(gradient7)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush25)
        gradient8 = QLinearGradient(0, 0, 1, 1)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(29, 29, 29, 255))
        gradient8.setColorAt(0.368715, QColor(31, 31, 31, 255))
        gradient8.setColorAt(0.675978, QColor(38, 38, 38, 255))
        gradient8.setColorAt(1, QColor(63, 63, 63, 255))
        brush26 = QBrush(gradient8)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush26)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush7)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush19)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush20)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush21)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush22)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush13)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush10)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush23)
#endif
        self.Loading_window_progressBar.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Anita  Semi-square"])
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.Loading_window_progressBar.setFont(font)
        self.Loading_window_progressBar.setCursor(QCursor(Qt.ArrowCursor))
        self.Loading_window_progressBar.setLayoutDirection(Qt.LeftToRight)
        self.Loading_window_progressBar.setAutoFillBackground(False)
        self.Loading_window_progressBar.setStyleSheet(u"font: 12pt \"Anita  Semi-square\";\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.Loading_window_progressBar.setValue(68)
        self.Loading_window_progressBar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Loading_window_progressBar.setInvertedAppearance(False)
        self.Loading_window_progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.label = QLabel(Loading_window)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 70, 721, 331))
        self.label.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 0), stop:1 rgba(255, 255, 255, 0));")
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setTextFormat(Qt.MarkdownText)
        self.label.setPixmap(QPixmap(u"LOGO ALGURIOS.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)

        self.retranslateUi(Loading_window)

        QMetaObject.connectSlotsByName(Loading_window)
    # setupUi

    def retranslateUi(self, Loading_window):
        Loading_window.setWindowTitle(QCoreApplication.translate("Loading_window", u"Dialog", None))
        self.Loading_window_progressBar.setFormat(QCoreApplication.translate("Loading_window", u"%p%", None))
        self.label.setText("")
    # retranslateUi

