# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'load1.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QProgressBar, QPushButton,
    QSizePolicy, QWidget)
import rsc_rc

class Ui_Loading_window(object):
    def setupUi(self, Loading_window):
        if not Loading_window.objectName():
            Loading_window.setObjectName(u"Loading_window")
        Loading_window.setWindowModality(Qt.WindowModal)
        Loading_window.resize(763, 261)
        Loading_window.setMinimumSize(QSize(763, 261))
        Loading_window.setMaximumSize(QSize(763, 261))
        Loading_window.setAcceptDrops(True)
        icon = QIcon()
        icon.addFile(u":/rsc/icone-alguros-1.png", QSize(), QIcon.Normal, QIcon.Off)
        Loading_window.setWindowIcon(icon)
        Loading_window.setWindowOpacity(1.000000000000000)
        Loading_window.setAutoFillBackground(False)
        Loading_window.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(13, 13, 13, 255), stop:0.368715 rgba(26, 26, 26, 255), stop:0.675978 rgba(42, 42, 42, 255), stop:1 rgba(51, 51, 51, 255));")
        Loading_window.setSizeGripEnabled(False)
        Loading_window.setModal(True)
        self.Loading_window_progressBar = QProgressBar(Loading_window)
        self.Loading_window_progressBar.setObjectName(u"Loading_window_progressBar")
        self.Loading_window_progressBar.setGeometry(QRect(20, 90, 721, 61))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Loading_window_progressBar.sizePolicy().hasHeightForWidth())
        self.Loading_window_progressBar.setSizePolicy(sizePolicy)
        palette = QPalette()
        gradient = QLinearGradient(0, 0, 1, 1)
        gradient.setSpread(QGradient.PadSpread)
        gradient.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient.setColorAt(0, QColor(13, 13, 13, 255))
        gradient.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient.setColorAt(1, QColor(51, 51, 51, 255))
        brush = QBrush(gradient)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        gradient1 = QLinearGradient(0, 0, 1, 1)
        gradient1.setSpread(QGradient.PadSpread)
        gradient1.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient1.setColorAt(0, QColor(126, 126, 126, 255))
        gradient1.setColorAt(1, QColor(255, 255, 255, 255))
        brush1 = QBrush(gradient1)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        brush2 = QBrush(QColor(6, 208, 164, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Light, brush2)
        brush3 = QBrush(QColor(0, 255, 255, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Active, QPalette.Dark, brush3)
        brush4 = QBrush(QColor(112, 112, 112, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Mid, brush4)
        gradient2 = QLinearGradient(0, 0, 1, 1)
        gradient2.setSpread(QGradient.PadSpread)
        gradient2.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient2.setColorAt(0, QColor(13, 13, 13, 255))
        gradient2.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient2.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient2.setColorAt(1, QColor(51, 51, 51, 255))
        brush5 = QBrush(gradient2)
        palette.setBrush(QPalette.Active, QPalette.Text, brush5)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush2)
        gradient3 = QLinearGradient(0, 0, 1, 1)
        gradient3.setSpread(QGradient.PadSpread)
        gradient3.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient3.setColorAt(0, QColor(13, 13, 13, 255))
        gradient3.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient3.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient3.setColorAt(1, QColor(51, 51, 51, 255))
        brush6 = QBrush(gradient3)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        gradient4 = QLinearGradient(0, 0, 1, 1)
        gradient4.setSpread(QGradient.PadSpread)
        gradient4.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient4.setColorAt(0, QColor(126, 126, 126, 255))
        gradient4.setColorAt(1, QColor(255, 255, 255, 255))
        brush7 = QBrush(gradient4)
        palette.setBrush(QPalette.Active, QPalette.Base, brush7)
        gradient5 = QLinearGradient(0, 0, 1, 1)
        gradient5.setSpread(QGradient.PadSpread)
        gradient5.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient5.setColorAt(0, QColor(126, 126, 126, 255))
        gradient5.setColorAt(1, QColor(255, 255, 255, 255))
        brush8 = QBrush(gradient5)
        palette.setBrush(QPalette.Active, QPalette.Window, brush8)
        palette.setBrush(QPalette.Active, QPalette.Shadow, brush2)
        palette.setBrush(QPalette.Active, QPalette.Highlight, brush2)
        brush9 = QBrush(QColor(0, 0, 0, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.HighlightedText, brush9)
        palette.setBrush(QPalette.Active, QPalette.Link, brush2)
        brush10 = QBrush(QColor(56, 56, 56, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush10)
        palette.setBrush(QPalette.Active, QPalette.ToolTipBase, brush2)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush4)
        gradient6 = QLinearGradient(0, 0, 1, 1)
        gradient6.setSpread(QGradient.PadSpread)
        gradient6.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient6.setColorAt(0, QColor(13, 13, 13, 255))
        gradient6.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient6.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient6.setColorAt(1, QColor(51, 51, 51, 255))
        brush11 = QBrush(gradient6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
#endif
        gradient7 = QLinearGradient(0, 0, 1, 1)
        gradient7.setSpread(QGradient.PadSpread)
        gradient7.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient7.setColorAt(0, QColor(13, 13, 13, 255))
        gradient7.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient7.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient7.setColorAt(1, QColor(51, 51, 51, 255))
        brush12 = QBrush(gradient7)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush12)
        gradient8 = QLinearGradient(0, 0, 1, 1)
        gradient8.setSpread(QGradient.PadSpread)
        gradient8.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient8.setColorAt(0, QColor(126, 126, 126, 255))
        gradient8.setColorAt(1, QColor(255, 255, 255, 255))
        brush13 = QBrush(gradient8)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush13)
        brush14 = QBrush(QColor(255, 255, 255, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush14)
        brush15 = QBrush(QColor(227, 227, 227, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Midlight, brush15)
        brush16 = QBrush(QColor(64, 65, 66, 255))
        brush16.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Dark, brush16)
        brush17 = QBrush(QColor(160, 160, 160, 255))
        brush17.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Mid, brush17)
        gradient9 = QLinearGradient(0, 0, 1, 1)
        gradient9.setSpread(QGradient.PadSpread)
        gradient9.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient9.setColorAt(0, QColor(13, 13, 13, 255))
        gradient9.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient9.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient9.setColorAt(1, QColor(51, 51, 51, 255))
        brush18 = QBrush(gradient9)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush18)
        brush19 = QBrush(QColor(255, 51, 51, 255))
        brush19.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush19)
        gradient10 = QLinearGradient(0, 0, 1, 1)
        gradient10.setSpread(QGradient.PadSpread)
        gradient10.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient10.setColorAt(0, QColor(13, 13, 13, 255))
        gradient10.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient10.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient10.setColorAt(1, QColor(51, 51, 51, 255))
        brush20 = QBrush(gradient10)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush20)
        gradient11 = QLinearGradient(0, 0, 1, 1)
        gradient11.setSpread(QGradient.PadSpread)
        gradient11.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient11.setColorAt(0, QColor(126, 126, 126, 255))
        gradient11.setColorAt(1, QColor(255, 255, 255, 255))
        brush21 = QBrush(gradient11)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush21)
        gradient12 = QLinearGradient(0, 0, 1, 1)
        gradient12.setSpread(QGradient.PadSpread)
        gradient12.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient12.setColorAt(0, QColor(126, 126, 126, 255))
        gradient12.setColorAt(1, QColor(255, 255, 255, 255))
        brush22 = QBrush(gradient12)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush22)
        brush23 = QBrush(QColor(105, 105, 105, 255))
        brush23.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Shadow, brush23)
        brush24 = QBrush(QColor(29, 84, 92, 255))
        brush24.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Highlight, brush24)
        brush25 = QBrush(QColor(240, 240, 240, 255))
        brush25.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.HighlightedText, brush25)
        brush26 = QBrush(QColor(0, 122, 244, 255))
        brush26.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Link, brush26)
        brush27 = QBrush(QColor(53, 54, 55, 255))
        brush27.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush27)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush16)
        brush28 = QBrush(QColor(208, 208, 208, 255))
        brush28.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush28)
        gradient13 = QLinearGradient(0, 0, 1, 1)
        gradient13.setSpread(QGradient.PadSpread)
        gradient13.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient13.setColorAt(0, QColor(13, 13, 13, 255))
        gradient13.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient13.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient13.setColorAt(1, QColor(51, 51, 51, 255))
        brush29 = QBrush(gradient13)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush29)
#endif
        gradient14 = QLinearGradient(0, 0, 1, 1)
        gradient14.setSpread(QGradient.PadSpread)
        gradient14.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient14.setColorAt(0, QColor(13, 13, 13, 255))
        gradient14.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient14.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient14.setColorAt(1, QColor(51, 51, 51, 255))
        brush30 = QBrush(gradient14)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush30)
        gradient15 = QLinearGradient(0, 0, 1, 1)
        gradient15.setSpread(QGradient.PadSpread)
        gradient15.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient15.setColorAt(0, QColor(126, 126, 126, 255))
        gradient15.setColorAt(1, QColor(255, 255, 255, 255))
        brush31 = QBrush(gradient15)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush31)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush2)
        palette.setBrush(QPalette.Disabled, QPalette.Midlight, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Dark, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Mid, brush4)
        gradient16 = QLinearGradient(0, 0, 1, 1)
        gradient16.setSpread(QGradient.PadSpread)
        gradient16.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient16.setColorAt(0, QColor(13, 13, 13, 255))
        gradient16.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient16.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient16.setColorAt(1, QColor(51, 51, 51, 255))
        brush32 = QBrush(gradient16)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush32)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush2)
        gradient17 = QLinearGradient(0, 0, 1, 1)
        gradient17.setSpread(QGradient.PadSpread)
        gradient17.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient17.setColorAt(0, QColor(13, 13, 13, 255))
        gradient17.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient17.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient17.setColorAt(1, QColor(51, 51, 51, 255))
        brush33 = QBrush(gradient17)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush33)
        gradient18 = QLinearGradient(0, 0, 1, 1)
        gradient18.setSpread(QGradient.PadSpread)
        gradient18.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient18.setColorAt(0, QColor(126, 126, 126, 255))
        gradient18.setColorAt(1, QColor(255, 255, 255, 255))
        brush34 = QBrush(gradient18)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush34)
        gradient19 = QLinearGradient(0, 0, 1, 1)
        gradient19.setSpread(QGradient.PadSpread)
        gradient19.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient19.setColorAt(0, QColor(126, 126, 126, 255))
        gradient19.setColorAt(1, QColor(255, 255, 255, 255))
        brush35 = QBrush(gradient19)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush35)
        palette.setBrush(QPalette.Disabled, QPalette.Shadow, brush9)
        palette.setBrush(QPalette.Disabled, QPalette.Highlight, brush24)
        palette.setBrush(QPalette.Disabled, QPalette.HighlightedText, brush25)
        palette.setBrush(QPalette.Disabled, QPalette.Link, brush26)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush27)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush16)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush28)
        gradient20 = QLinearGradient(0, 0, 1, 1)
        gradient20.setSpread(QGradient.PadSpread)
        gradient20.setCoordinateMode(QGradient.ObjectBoundingMode)
        gradient20.setColorAt(0, QColor(13, 13, 13, 255))
        gradient20.setColorAt(0.368715, QColor(26, 26, 26, 255))
        gradient20.setColorAt(0.675978, QColor(42, 42, 42, 255))
        gradient20.setColorAt(1, QColor(51, 51, 51, 255))
        brush36 = QBrush(gradient20)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush36)
#endif
        self.Loading_window_progressBar.setPalette(palette)
        font = QFont()
        font.setFamilies([u"Anita  Semi-square"])
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.Loading_window_progressBar.setFont(font)
        self.Loading_window_progressBar.setCursor(QCursor(Qt.ArrowCursor))
        self.Loading_window_progressBar.setLayoutDirection(Qt.LeftToRight)
        self.Loading_window_progressBar.setAutoFillBackground(False)
        self.Loading_window_progressBar.setStyleSheet(u"font: 12pt \"Anita  Semi-square\";\n"
"image: url(:/icones/LOGO ALGURIOS.png);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(126, 126, 126, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(13, 13, 13, 255), stop:0.368715 rgba(26, 26, 26, 255), stop:0.675978 rgba(42, 42, 42, 255), stop:1 rgba(51, 51, 51, 255));\n"
"border-color: rgb(112, 112, 112);\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.Loading_window_progressBar.setValue(0)
        self.Loading_window_progressBar.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.Loading_window_progressBar.setTextVisible(True)
        self.Loading_window_progressBar.setInvertedAppearance(False)
        self.Loading_window_progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.pushButton_endLoad = QPushButton(Loading_window)
        self.pushButton_endLoad.setObjectName(u"pushButton_endLoad")
        self.pushButton_endLoad.setGeometry(QRect(280, 190, 201, 41))
        self.pushButton_endLoad.setStyleSheet(u"color: rgb(6, 208, 164);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(6, 208, 164, 255), stop:1 rgba(3, 102, 80, 255));\n"
"selection-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(39, 39, 39, 255), stop:0.368715 rgba(57, 57, 57, 255), stop:0.675978 rgba(66, 66, 66, 255), stop:1 rgba(78, 78, 78, 255));\n"
"selection-background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(6, 208, 164, 255), stop:1 rgba(3, 102, 80, 255));")
        icon1 = QIcon()
        icon1.addFile(u":/icones/icons8-caixa-de-selec\u00e7\u00e3o-seleccionada-2-50-3.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_endLoad.setIcon(icon1)

        self.retranslateUi(Loading_window)

        self.pushButton_endLoad.setDefault(True)


        QMetaObject.connectSlotsByName(Loading_window)
    # setupUi

    def retranslateUi(self, Loading_window):
        Loading_window.setWindowTitle(QCoreApplication.translate("Loading_window", u"Loading...", None))
#if QT_CONFIG(tooltip)
        self.Loading_window_progressBar.setToolTip(QCoreApplication.translate("Loading_window", u"<html><head/><body><p>Loading...</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.Loading_window_progressBar.setFormat(QCoreApplication.translate("Loading_window", u"%p%", None))
#if QT_CONFIG(tooltip)
        self.pushButton_endLoad.setToolTip(QCoreApplication.translate("Loading_window", u"<html><head/><body><p>Continue</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.pushButton_endLoad.setText(QCoreApplication.translate("Loading_window", u"Continue", None))
    # retranslateUi

